---
- project:
    templates:
      - publish-stx-docs
      - stx-release-notes-jobs
      - stx-bandit-jobs
    check:
      jobs:
        - gui-tox-linters
        - gui-tox-pep8
        - gui-tox-pylint
    gate:
      jobs:
        - gui-tox-linters
        - gui-tox-pep8
        - gui-tox-pylint
    post:
      jobs:
        - stx-gui-upload-git-mirror

- job:
    name: gui-tox-linters
    parent: tox
    description: |
      Run linters
    nodeset: debian-bullseye
    vars:
      tox_envlist: linters

- job:
    name: gui-tox-pep8
    parent: tox
    description: |
      Check conformance with pep8
    nodeset: debian-bullseye
    vars:
      tox_envlist: pep8

- job:
    name: gui-tox-pylint
    parent: tox
    description: Run pylint for gui repo
    nodeset: debian-bullseye
    vars:
      tox_envlist: pylint
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'  # yamllint disable-line rule:line-length
      tox_environment:
        STX_DC_CLIENT: distcloud-client
      bindep_profile: pylint
    required-projects:
      - starlingx/config
      - starlingx/distcloud-client
      - starlingx/fault
      - starlingx/ha
      - starlingx/nfv
      - starlingx/root
      - starlingx/utilities

- job:
    name: stx-gui-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/gui to
      github.com/starlingx/gui
    vars:
      git_mirror_repository: starlingx/gui
    secrets:
      - name: git_mirror_credentials
        secret: stx-gui-github-secret3
        pass-to-parent: true

- secret:
    name: stx-gui-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - ANJuTCbZrpCmLs2+fPSfgJH+6D7rGbreMbhxH1JZ0TLvt6oOml8JEoKP61eT9n7kcjzEN
          BdvsyCmvbS3zRg9iQ0yqA3/wh6+jE31oS5KSJNBogCDVkcZ1I9ogvvpPCKcmm3v4iWbn0
          Q78nzhCVxwGedfi/vRqiQzXEPVfx/rml54dQqz+mpRQLNzZvqUYuqrbcbWUXd4K8CbiZE
          IjTH9vkqAP88KfrXDbd29BI/DRsB4uDqQPZsB2IfICQJSFQd6uG/VmGXgu1w3NVIJGgOs
          VqMt22Urhy5kPYSRK30lwTpIxAaYca4XV8lYUwyp9AWXrZriUnGvoIdGag5Xo7gigYUJQ
          BhfRLtzMRmo16yUqi0nws/Sk/Szv59syYAu5WNy/+TGKq1WYYePfBuBDk2OnJxyRcJdwe
          YVHJN7x0H0crZhhvTkh1pbBgBQrhCQlZKXHnfJ1tkwvQxhrPxerjYrmLLLDrLPMJ5JYzk
          0Mnw30QBhzl1Z1XXIpcNTTALvo8mFNfGPQu96afxKF6jCtaLP0kXgGErwkDWg8iMGxO3I
          3q//S7ceV6a996HpBXC7Inrm9FXogHOTpsc28hFO+H+T7zdUGTHMWKkq16gSg6gWYmOYV
          TX3/x7CyxyQYUMpmxDAUqKWutw71znEBjXqkHo16wWCiM6HV54eS85zpq613dI=
        - HQk2Q8qJB1B9o+HD1s9vc9b8oXwGkZAJGZ65B94IDkqUA//nZGJWGnDK+uBfjjvxhPCom
          eHzc0BUYutqtSzlbkv3mVCGG0f+qRAAm8t/EtMwobGgcXyESm6PBbXT0/PN5aRZM3iBRU
          6+ojloCg46pEesQRzBfV4Wnj2nYoVb0YyjdcysP49L1hN5fVsKtzeC64VVdlUbv2gOLhz
          MnAZOldZqIq4ettC0V6s9HAgyPZIyCTAUplyIw1fAfadW+Ygr2YIFI6gw9AOcEeWXJctx
          4RnvmtN/JT9L6H1zHcN0ncUD3M2YLsIJ2U8t1pNfVd1Z1WtEe5WHbPbysLN+rkn5IIEON
          WF5nsSdsFh6wAkx0/bJCSRUm4mvGjOK7e7J242lin4zs+UKV0hElGXdN92znQPdSilx9L
          xzrGvGsQzy7370sbSmbJbl3d6x7d1ObOAuBaQYirPrYnJ6XeIlQ+m/n8gETJyREMvKtlQ
          LZrMeAnc1G8bg++p4p6kIt2kjJpPmKSV/8JzdUJZ2jFPihcynLTSBWvo1OtG+k/v66Aen
          7G0PG/MUylxqBIA75qHuTA+jwRcSdgCu8xIgbt/DJmJEctfJBWP4ggUuNSLSyqPMgu51K
          /MbtOobNgE0lv2gxz7XG8xSFBYU8g2tW1fp47fuwAb8iWt3ox/s6Y0cI5su8kQ=
        - Bijviatcx1BE0D/vA6+0gxkpcdzYtIz9321qREbujwTL+MaL6tzmEJVhwQn97ZD2wybH+
          H3VcEoHKVTFL+lvoufXsVar/i2btAQUep3kFcUkNFiTVglx2pfPPdZNlraXryKL1Xdkec
          oB6tI5xBfnvhOLvZtZEWgScvl5rc3E8lT6v59eyfSL29ydYgZ1Wqv/ygYmAMcIB2GaBCh
          jduIlNtZnLpDmOyQ7PaTPG/alxKs41RzZBbDZgB7X1Q7oNbb4ldpgXREVlZQciwgrRKYZ
          77XP9dkC54M8szkUvhnMGJs0fqVJC8zsxparQPYB1owQAi/t5z5/rV6fbfvZhEvj3piCo
          k8Grtu3nzuvDynPAWNWB6OOBthQ9mvS86yxqCwbqBny9JbQkbUnhUGZvNwX9v3TQpBm3f
          pygHSVmUNQ0g7WskWgPSLbcbKqNysvbLC7OO2eQmLdx9Cg8P3PSSSkG5I5Qc1woFmjxdK
          xdVi7dnTXDe2M7igvod61MIZoGMK6UsIYxkS8Ock03dIdxR41ZkDGqUhgUgQ2TqFoKtdK
          +2bDW/SrNuilroZ1+pOa6Nuyus2dUSG7rH3FY2Gm25icd3+iZ+3LbQerL58HwAvK+g+TO
          1789jsdTkBsuQREuM/r9nwfSI2WWZoT5YUGh2LAfQjcE7rmd68onKMTNPCrs9k=
        - aAT9Upd8Yh6UUYxSk2You9m8wpgT24/1gRAVm0q+DKdH5Z482rqIaPBjuTxIEtxHUXTGC
          vDI8Yj3bXMd0qPxEgJpECSUw9EZ7qINlMeUp5WzRhxdSChy6d6iHiQKaSdf4dMwYtPrs0
          qgOCi8mg7k8Ytz8cyZpBYremMKUflyK7HlZC4Mfcq7cPa0lVnUAmkMLuJrpMfORSOBNTU
          ulg60kd6OsmtC74y1CvTraWA1ajQcpKQe9tZYoThVmZvSam9M/Z3ePs6QyzZbgX2vNXwE
          yupEzMmiF8obsGTqHvUEWqUH3Ef7tMqELsZAJKexx3eKTzllVUti8v2DDtmhpZM4Brsjz
          vS5Yh8JKEEqeQPHlXEiRtKilijiMqP+hX6SFZCm438hW7dhQvuNX2g69B7GERMJF9FdG+
          1Z0alMZe3RRPOJ2LLTVh+C1oDeWgpTN/1fSqbJ/RgC8rwPcyR1B+P8vYecQjIApidk697
          AHmDwfY7hT8jLeO3XelVUhKLwAZc5wCvzcdXyv472wec3h1cWmQjLkSHIGMl0hcH6raDT
          UpTfQDlyE/TPzc3x/FDNcH1YwAuYEXYTHrIAYM/u35swCJUkRBeVw3xg7TDPo2fHmjMFB
          F0wOQFM3H3U/XyPhbdvEb1I5mwk4SstHTZdj0XX4sSRqYdVAvTEaskFNcXqo3Q=
        - WXrWtXUEuCdIejLHLcjrpVv+ruua6PxHmycANYStCPyNNrQbRT/QYgQI8WdB/gaGX67D6
          EDq86eDFG1zBhp/N/2bGg/4RJyDD5LUuHbGq2H72cUU6c1P1cjxztviIeL6Wkam9tA0YF
          Je359xJlo6PJ6APzhByH1p9U0hU71pchfUg8nAQm6Vg/8jO6KFHNTivX+OhgJ9NnF4ZNk
          jdqaRJeI3iWJhvktBMhnB/8UaamHy9m420NaFOuoohmMtTG9tN+ERkm3wuhKZu1yoB7lL
          oLuIoofKZn4fFN/CpXOmNtH1eiomlGKHWbKL37UNxtxLnOeAth5tKWAWoruXvA9cD2RHI
          yIgvWlQPz5BoSbKxLtpzSIRNkwuu+v8G+dAJw1VulrW+IMhz8UpAM8bytc5FGXUSMUial
          /v7J7YWNRPM5ZSpAZSAlXJdPVyiJnA5nE4RqjBVDEalJm+3JlowWZ5g1eBmcGHsqv+y/s
          pgImEF+2VCLr9pNW/jN1QfDvZLsouT5WSqxoEeh6gMdXUMRcLqhliQGq1m4Ia1pFbi0ZJ
          qot/B9X+1RTV2U460BuyyvX/CoRJnbttnEZkiCKqllaEXcog8T+qC4LvGcn4wZ8A+g12g
          eG0Vr2Ybj33OHs8uTmMEGfcbv8+MYtUlrAITUMNx/7kYQwMj/4uuBajvmVQC8Q=
        - rBKS7k3QZFaV/Hp6MWyj6qLPcs198CVb1rQ9QmT4M9amW1tkcJ5AaAd69pEui9y9VaHeG
          zUHbzydfR3Ci2eLOTTaAT9rz3omnQikEK3d66PTZRzdJsd3xB9TloP0Nuty5IrAnZssG0
          vXCT40PhjY5vCqsAJJaqmL+WvG7M7gVtkCxEiVl6geUP4W3R9MlMjc2pqDG34KOTZoLU+
          983LG/1QIwZTyv/9mshWZoZ/heHLvbB5U7eOFtyu4yZ0LGfF6zvoaEr8HUSsaKGso1pyY
          flkUvy68D6SFqJTuTHqqog8pksqq5I+aC2U2X+UlCgs/iN6gW24vymxR8BjnuloOoOWfC
          ORCi4B2wM8Jf39hohDy3cqXNiH4gg2uJ1po0oPmRuJwrMy9g+TUgkPerfTKRcI6Hr+X65
          RJ3t5kOwIyo8TfOEr1j7KfXFZqrIiVbuvcz8OCirw2g2sK/dtYY4+PNwCidag7pSfpWmb
          FEfbMwbhqqzK5SkN/gvPSIjAUutRY4zUU+tjLrUcJiINiNKLEtjaZcUy2nQjkeFkRcspp
          Efe28gXOK45+XTxMeihhvEHo1K5D0qwnyMo6Ohids5bb25ydJ9tooB8g0xnLNwU4nNBFE
          5SDPXZszcUXe5SuwfyuMpvDik8cp3BKnfq6vcEpRZFGQBbe3iqQCsUe4lcKIrA=
        - O3R4N2zVySNT167QxRIjKsftPYI6UNsnZoiXW/rq4DxGrX+DW0OUVU/bIaafRy8vAWzkt
          HPPoV27pOAlJVr1H+zEkltsYOJD7al+XPE2w07pHJ5Sx8STuPw3VsBZMcjryDqAVPVyT0
          sD7qkk5DZON4wpnh/rUbNKOxUeaUZmXSa6nQacHpF3o6e+SCDrIyOEtOwNl0oM6RHsta3
          iit8LRWOZ2f3XFpPXJdAFBI68LhL0Gucr9+gu7QZ7xD9pqUyGpMtkTOt2SBCZWPjr8rdz
          ypWVcaWnh5biyfObh0fWCk32Z4BTxS/DP52b9XNvnqwuCo+ND9l/1lCPNmJ8ziJxjPbm4
          laTLZC66dLnLYqi6MkTP7GNvA9+CJAk0p4BO4bNRDQxoF+FXDfebfuU7M3JUWdMSGnr+8
          zNCQGOImi2VT3xnr6qUMMSI4LdghSdJBmfeHY0NjKKBjzmLJOHSO/+u7GU39wFalNW64v
          jJRRMj79ejEoyuZ7VZANw+rmAYey06n13y83zZ5P0owoU6UMMlyaW203FZPLb8tonOZXH
          KvFcYFzqdIbgt4j3u1VR9R5KQAo352fH9Jd2x/M4WlX1Q3eGK9w60DrsozbYTqnnxIM3w
          Aht1gGWj8UJurx1BO2j0a/uke2vnqC2q/lE3737XeMy8c9/l9/vb8VRUMSYx6A=
