---
- project:
    templates:
      - publish-stx-docs
      - stx-release-notes-jobs
    check:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-linters
        - stx-gui-pylint
    gate:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-linters
        - stx-gui-pylint

- job:
    name: stx-gui-pylint
    parent: openstack-tox-pylint
    description: Run pylint for stx-gui
    vars:
      tox_envlist: pylint
      tox_environment:
        STX_DC_CLIENT: distcloud-client
    required-projects:
      - starlingx/config
      - starlingx/distcloud-client
      - starlingx/fault
      - starlingx/ha
      - starlingx/nfv
      - starlingx/update
      - starlingx/utilities
