usr/lib/python3/dist-packages/openstack_dashboard/enabled
usr/share/openstack-dashboard/themes/starlingx
etc/openstack-dashboard/local_settings.d
usr/lib/python3/dist-packages/openstack_dashboard/starlingx_templates/*
usr/lib/python3/dist-packages/openstack_dashboard/overrides/*

usr/lib/python3/dist-packages/starlingx_dashboard-*.egg-info/*
usr/lib/python3/dist-packages/starlingx_dashboard/*

/var/log/horizon
